/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_example_jjung_snowflakes_wallpaper_particles_EmitterNative
#define _Included_com_example_jjung_snowflakes_wallpaper_particles_EmitterNative
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL
Java_net_wandroid_snowflakes_wallpaper_particles_EmitterNative_onSurfaceCreated
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL
Java_net_wandroid_snowflakes_wallpaper_particles_EmitterNative_onDrawFrame
  (JNIEnv *, jobject, jint,jint,jfloat);


#ifdef __cplusplus
}
#endif
#endif